// Aivee Editorial OS - Mock Data
import { Issue, Story, Source, LinkedInPost, ReviewItem, EditorialChecklist } from './types';

// Seed data for development
export const mockIssues: Issue[] = [
  {
    id: 'issue-001',
    issue_number: 1,
    title: 'The Platform Consolidation Wave',
    subtitle: 'What Autodesk, Trimble, and Emerging Markets Mean for Your BIM Practice',
    weekly_angle: 'Major vendors simplifying while adding AI',
    content_pillar: 'industry_intelligence',
    status: 'in_review',
    readiness_score: 72,
    linkedin_status: 'drafted',
    created_at: '2026-03-22T00:00:00Z',
    updated_at: '2026-03-22T14:00:00Z',
  },
  {
    id: 'issue-002',
    issue_number: 2,
    title: 'ISO 19650 Deep Dive',
    subtitle: 'Understanding the Golden Thread',
    weekly_angle: 'Standards explainer for practical application',
    content_pillar: 'standards_authority',
    status: 'collecting_signals',
    readiness_score: 15,
    linkedin_status: 'not_started',
    created_at: '2026-03-23T00:00:00Z',
    updated_at: '2026-03-23T00:00:00Z',
  },
];

// Additional unassigned stories for research feed
const unassignedStories: Story[] = [
  {
    id: 'story-006',
    title: 'Bentley Systems Announces New Infrastructure AI Tools',
    source_name: 'Bentley Blog',
    source_url: 'https://bentley.com',
    source_type: 'official_vendor',
    published_date: '2026-03-20',
    detected_date: '2026-03-23',
    summary: 'Bentley adds AI-powered analysis to their infrastructure suite.',
    why_it_matters: 'Expands AI capabilities in civil infrastructure design.',
    who_it_affects: 'Civil engineers, infrastructure designers',
    action_takeaway: 'Evaluate new AI features for infrastructure projects.',
    category: 'Product Update',
    tags: ['Bentley', 'AI', 'Infrastructure'],
    credibility_score: 8,
    relevance_score: 7,
    novelty_score: 6,
    actionability_score: 7,
    overall_score: 7.10,
    disposition: 'save_for_later',
    created_at: '2026-03-23T00:00:00Z',
    updated_at: '2026-03-23T00:00:00Z',
  },
  {
    id: 'story-007',
    title: 'UK Government Updates BIM Mandate Requirements',
    source_name: 'BSI Blog',
    source_url: 'https://bsi.com',
    source_type: 'standards_body',
    published_date: '2026-03-19',
    detected_date: '2026-03-23',
    summary: 'Updated requirements for government construction projects.',
    why_it_matters: 'New compliance requirements for UK projects.',
    who_it_affects: 'UK contractors, consultants',
    action_takeaway: 'Review updated requirements.',
    category: 'Standards',
    tags: ['BIM', 'UK', 'BSI', 'Standards'],
    credibility_score: 9,
    relevance_score: 8,
    novelty_score: 5,
    actionability_score: 8,
    overall_score: 7.65,
    disposition: 'use_this_week',
    created_at: '2026-03-23T00:00:00Z',
    updated_at: '2026-03-23T00:00:00Z',
  },
  {
    id: 'story-008',
    title: 'New Revit 2026 Features for MEP Coordination',
    source_name: 'Autodesk University',
    source_url: 'https://autodesk.com/university',
    source_type: 'official_vendor',
    published_date: '2026-03-18',
    detected_date: '2026-03-23',
    summary: 'New MEP coordination tools in Revit 2026.',
    why_it_matters: 'Improved coordination workflows for mechanical, electrical, plumbing.',
    who_it_affects: 'MEP engineers, coordinators',
    action_takeaway: 'Test new coordination features.',
    category: 'Product Update',
    tags: ['Revit', 'MEP', 'Autodesk'],
    credibility_score: 8,
    relevance_score: 8,
    novelty_score: 5,
    actionability_score: 7,
    overall_score: 7.10,
    disposition: 'save_for_later',
    created_at: '2026-03-23T00:00:00Z',
    updated_at: '2026-03-23T00:00:00Z',
  },
];

export const mockStories: Story[] = [
  {
    id: 'story-001',
    issue_id: 'issue-001',
    title: 'Autodesk Construction Cloud Merges Into Forma',
    source_name: 'Autodesk News',
    source_url: 'https://autodesk.com/news',
    source_type: 'official_vendor',
    published_date: '2026-02-25',
    detected_date: '2026-03-22',
    summary: 'Autodesk consolidating Construction Cloud into Forma with geometry-based AI assistants.',
    why_it_matters: 'End of the 30-product ecosystem era. AI assistants will understand building context.',
    who_it_affects: 'VDC managers, project managers in Autodesk ecosystem',
    action_takeaway: 'Start mapping workflows to Forma now.',
    category: 'Product Update',
    tags: ['Autodesk', 'Forma', 'AI', 'BIM'],
    credibility_score: 9,
    relevance_score: 9,
    novelty_score: 7,
    actionability_score: 8,
    overall_score: 8.35,
    disposition: 'use_this_week',
    created_at: '2026-03-22T00:00:00Z',
    updated_at: '2026-03-22T00:00:00Z',
  },
  {
    id: 'story-002',
    issue_id: 'issue-001',
    title: 'Tekla 2026 Brings AI-Powered Workflow Enhancements',
    source_name: 'Engineering.com',
    source_url: 'https://engineering.com',
    source_type: 'industry_publication',
    published_date: '2026-03-11',
    detected_date: '2026-03-22',
    summary: 'Trimble unveiled Tekla 2026 with new AI tools for structural engineering.',
    why_it_matters: 'Incremental AI approach - realistic for structural workflows where human judgment rules.',
    who_it_affects: 'Structural engineers, detailers, fabricators',
    action_takeaway: 'Test new AI features on low-risk project first.',
    category: 'Product Update',
    tags: ['Tekla', 'Trimble', 'AI', 'Structural'],
    credibility_score: 8,
    relevance_score: 8,
    novelty_score: 6,
    actionability_score: 7,
    overall_score: 7.35,
    disposition: 'use_this_week',
    created_at: '2026-03-22T00:00:00Z',
    updated_at: '2026-03-22T00:00:00Z',
  },
  {
    id: 'story-003',
    issue_id: 'issue-001',
    title: 'Kazakhstan Builds National Digital Construction Ecosystem',
    source_name: 'The Astana Times',
    source_url: 'https://astanatimes.com',
    source_type: 'industry_publication',
    published_date: '2026-03-10',
    detected_date: '2026-03-22',
    summary: 'Government-driven BIM adoption in Central Asia.',
    why_it_matters: 'Emerging markets skipping legacy workflows - new opportunities for international firms.',
    who_it_affects: 'International engineering firms, BIM consultants',
    action_takeaway: 'Keep eye on emerging market BIM mandates.',
    category: 'Industry Moves',
    tags: ['BIM', 'Kazakhstan', 'Government', 'Emerging Markets'],
    credibility_score: 7,
    relevance_score: 6,
    novelty_score: 8,
    actionability_score: 5,
    overall_score: 6.45,
    disposition: 'use_this_week',
    created_at: '2026-03-22T00:00:00Z',
    updated_at: '2026-03-22T00:00:00Z',
  },
  {
    id: 'story-004',
    issue_id: 'issue-001',
    title: 'Mobile 3D BIM Access Goes Mainstream',
    source_name: 'Construction Dive',
    source_url: 'https://constructiondive.com',
    source_type: 'industry_publication',
    published_date: '2026-03-18',
    detected_date: '2026-03-22',
    summary: 'Viable mobile 3D BIM visualization and real-time site-data integration.',
    why_it_matters: 'Field access to live BIM data - bridging design-construction gap.',
    who_it_affects: 'Site supervisors, field engineers, construction managers',
    action_takeaway: 'Test one mobile BIM tool on next project.',
    category: 'Industry Moves',
    tags: ['Mobile', 'BIM', 'Field', 'Visualization'],
    credibility_score: 8,
    relevance_score: 7,
    novelty_score: 6,
    actionability_score: 8,
    overall_score: 7.30,
    disposition: 'use_this_week',
    created_at: '2026-03-22T00:00:00Z',
    updated_at: '2026-03-22T00:00:00Z',
  },
  {
    id: 'story-005',
    issue_id: 'issue-001',
    title: 'QikBIM Converts 2D to 3D',
    source_name: 'Stock Titan',
    source_url: 'https://stocktitan.com',
    source_type: 'industry_publication',
    published_date: '2026-01-15',
    detected_date: '2026-03-22',
    summary: 'OFA Group QikBIM converts 2D blueprints into BIM models in hours.',
    why_it_matters: 'Solving legacy drawing problem - automating digitization of existing 2D archives.',
    who_it_affects: 'Firms with large 2D archives, renovation specialists',
    action_takeaway: 'Evaluate QikBIM if you have legacy drawings.',
    category: 'AI Tool',
    tags: ['AI', 'BIM', '2D', 'Conversion'],
    credibility_score: 6,
    relevance_score: 7,
    novelty_score: 7,
    actionability_score: 6,
    overall_score: 6.55,
    disposition: 'save_for_later',
    created_at: '2026-03-22T00:00:00Z',
    updated_at: '2026-03-22T00:00:00Z',
  },
];

export const mockSources: Source[] = [
  {
    id: 'src-001',
    name: 'Autodesk',
    source_type: 'official_vendor',
    category: 'Software',
    trust_tier: 'Tier 1',
    website_url: 'https://autodesk.com',
    notes: 'Major AEC software vendor',
    times_used: 12,
    average_quality_score: 9,
    last_used_at: '2026-03-22',
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-03-22T00:00:00Z',
  },
  {
    id: 'src-002',
    name: 'Construction Dive',
    source_type: 'industry_publication',
    category: 'News',
    trust_tier: 'Tier 2',
    website_url: 'https://constructiondive.com',
    notes: 'Industry news outlet',
    times_used: 8,
    average_quality_score: 7,
    last_used_at: '2026-03-22',
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-03-22T00:00:00Z',
  },
  {
    id: 'src-003',
    name: 'ISO',
    source_type: 'standards_body',
    category: 'Standards',
    trust_tier: 'Tier 1',
    website_url: 'https://iso.org',
    notes: 'International standards body',
    times_used: 5,
    average_quality_score: 10,
    last_used_at: '2026-03-15',
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-03-15T00:00:00Z',
  },
  {
    id: 'src-004',
    name: 'Bentley Systems',
    source_type: 'official_vendor',
    category: 'Software',
    trust_tier: 'Tier 1',
    website_url: 'https://bentley.com',
    notes: 'Infrastructure software provider',
    times_used: 4,
    average_quality_score: 8,
    last_used_at: '2026-03-20',
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-03-20T00:00:00Z',
  },
  {
    id: 'src-005',
    name: 'BSI',
    source_type: 'standards_body',
    category: 'Standards',
    trust_tier: 'Tier 1',
    website_url: 'https://bsi.com',
    notes: 'UK standards body',
    times_used: 3,
    average_quality_score: 9,
    last_used_at: '2026-03-19',
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-03-19T00:00:00Z',
  },
  {
    id: 'src-006',
    name: 'The BIM Journal',
    source_type: 'industry_publication',
    category: 'Publication',
    trust_tier: 'Tier 2',
    website_url: 'https://bimjournal.com',
    notes: 'BIM-focused publication',
    times_used: 6,
    average_quality_score: 8,
    last_used_at: '2026-03-10',
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-03-10T00:00:00Z',
  },
  {
    id: 'src-007',
    name: 'Engineering.com',
    source_type: 'industry_publication',
    category: 'News',
    trust_tier: 'Tier 2',
    website_url: 'https://engineering.com',
    notes: 'Engineering news',
    times_used: 7,
    average_quality_score: 7,
    last_used_at: '2026-03-11',
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-03-11T00:00:00Z',
  },
  {
    id: 'src-008',
    name: 'buildingSMART',
    source_type: 'standards_body',
    category: 'Standards',
    trust_tier: 'Tier 1',
    website_url: 'https://buildingsmart.org',
    notes: 'Open BIM standards',
    times_used: 4,
    average_quality_score: 9,
    last_used_at: '2026-03-08',
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-03-08T00:00:00Z',
  },
];

export const mockLinkedInPosts: LinkedInPost[] = [
  {
    id: 'li-001',
    issue_id: 'issue-001',
    main_post: `🚨 The BIM platform consolidation is happening faster than expected.

Autodesk just folded Construction Cloud into Forma. Tekla added AI without rewriting everything. Kazakhstan went digital in one move.

What does this mean for you?

1. If you're on Autodesk → you're now on Forma. Start learning it.
2. If you're on Tekla → AI is coming incrementally, not as a revolution.
3. If you do international work → emerging markets are skipping legacy workflows.

The next 12 months will sort out who's adapted and who hasn't.

🔗 Subscribe to Aivee Weekly for practical BIM and AI insights delivered every Sunday.`,
    hook_variant_1: 'The platform consolidation wave is here',
    hook_variant_2: 'Autodesk just made a huge move',
    hook_variant_3: 'What Kazakhstan going digital means for your BIM practice',
    cta_variant_1: 'Subscribe to Aivee Weekly',
    cta_variant_2: 'Read the full issue',
    hashtags: '#BIM #AEC #AI #ConstructionTech #DigitalTransformation',
    status: 'drafted',
    created_at: '2026-03-22T00:00:00Z',
    updated_at: '2026-03-22T00:00:00Z',
  },
];

export const mockReviewItems: ReviewItem[] = [
  {
    id: 'rev-001',
    issue_id: 'issue-001',
    item_type: 'fact_check',
    label: 'Kazakhstan story verification',
    description: 'Verify if formal mandate or softer government initiative',
    status: 'open',
    priority: 'medium',
    created_at: '2026-03-22T00:00:00Z',
    updated_at: '2026-03-22T00:00:00Z',
  },
  {
    id: 'rev-002',
    issue_id: 'issue-001',
    item_type: 'title_approval',
    label: 'Newsletter title approval',
    description: 'Confirm title works for audience',
    status: 'resolved',
    priority: 'low',
    created_at: '2026-03-22T00:00:00Z',
    updated_at: '2026-03-22T00:00:00Z',
  },
];

export const mockChecklist: EditorialChecklist[] = [
  { id: 'chk-001', issue_id: 'issue-001', item_label: 'Enough sources (3+)', item_key: 'enough_sources', is_complete: true, sort_order: 1, created_at: '', updated_at: '' },
  { id: 'chk-002', issue_id: 'issue-001', item_label: '3+ strong stories', item_key: 'strong_stories', is_complete: true, sort_order: 2, created_at: '', updated_at: '' },
  { id: 'chk-003', issue_id: 'issue-001', item_label: 'Standards section included', item_key: 'standards_section', is_complete: true, sort_order: 3, created_at: '', updated_at: '' },
  { id: 'chk-004', issue_id: 'issue-001', item_label: 'AI section included', item_key: 'ai_section', is_complete: true, sort_order: 4, created_at: '', updated_at: '' },
  { id: 'chk-005', issue_id: 'issue-001', item_label: 'CTA included', item_key: 'cta_included', is_complete: true, sort_order: 5, created_at: '', updated_at: '' },
  { id: 'chk-006', issue_id: 'issue-001', item_label: 'LinkedIn post drafted', item_key: 'linkedin_drafted', is_complete: true, sort_order: 6, created_at: '', updated_at: '' },
  { id: 'chk-007', issue_id: 'issue-001', item_label: 'No unresolved fact-check flags', item_key: 'no_factcheck_flags', is_complete: false, sort_order: 7, created_at: '', updated_at: '' },
];

// All stories including unassigned
const allStories = [...mockStories, ...unassignedStories];

// Editorial data store (in-memory for now)
export const editorialData = {
  issues: mockIssues,
  stories: allStories,
  sources: mockSources,
  linkedinPosts: mockLinkedInPosts,
  reviewItems: mockReviewItems,
  checklist: mockChecklist,
};

// Database functions (mock for now, Supabase ready)
export const db = {
  issues: {
    getAll: () => Promise.resolve(mockIssues),
    getById: (id: string) => Promise.resolve(mockIssues.find(i => i.id === id)),
    getCurrent: () => Promise.resolve(mockIssues.find(i => i.status !== 'archived')),
  },
  stories: {
    getAll: () => Promise.resolve(mockStories),
    getByIssue: (issueId: string) => Promise.resolve(mockStories.filter(s => s.issue_id === issueId)),
    getShortlisted: (issueId: string) => Promise.resolve(mockStories.filter(s => s.issue_id === issueId && s.disposition === 'use_this_week')),
  },
  sources: {
    getAll: () => Promise.resolve(mockSources),
  },
  linkedinPosts: {
    getByIssue: (issueId: string) => Promise.resolve(mockLinkedInPosts.find(p => p.issue_id === issueId)),
  },
  reviewItems: {
    getByIssue: (issueId: string) => Promise.resolve(mockReviewItems.filter(r => r.issue_id === issueId)),
  },
  checklist: {
    getByIssue: (issueId: string) => Promise.resolve(mockChecklist.filter(c => c.issue_id === issueId)),
  },
};
